// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentProgram.Data;

namespace SacramentProgram.Migrations
{
    [DbContext(typeof(SacramentProgramContext))]
    [Migration("20200721160049_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentProgram.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccompanimentID")
                        .HasColumnType("int");

                    b.Property<int>("ClosingPrayerIdID")
                        .HasColumnType("int");

                    b.Property<int>("ClosingSongID")
                        .HasColumnType("int");

                    b.Property<int>("ConductingID")
                        .HasColumnType("int");

                    b.Property<int?>("IntermediateSongID")
                        .HasColumnType("int");

                    b.Property<int>("LeadingMusicID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MusicalNumberID")
                        .HasColumnType("int");

                    b.Property<int>("OpeningPrayerID")
                        .HasColumnType("int");

                    b.Property<int>("OpeningSongID")
                        .HasColumnType("int");

                    b.Property<int>("PresidingID")
                        .HasColumnType("int");

                    b.Property<int>("SacramentSongID")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccompanimentID");

                    b.HasIndex("ClosingPrayerIdID");

                    b.HasIndex("ClosingSongID");

                    b.HasIndex("ConductingID");

                    b.HasIndex("IntermediateSongID");

                    b.HasIndex("LeadingMusicID");

                    b.HasIndex("MusicalNumberID");

                    b.HasIndex("OpeningPrayerID");

                    b.HasIndex("OpeningSongID");

                    b.HasIndex("PresidingID");

                    b.HasIndex("SacramentSongID");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("SacramentProgram.Models.MusicalNum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Performer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SongID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SongID");

                    b.ToTable("MusicalNum");
                });

            modelBuilder.Entity("SacramentProgram.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BroOrSis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SacramentProgram.Models.Song", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("SacramentProgram.Models.Speaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MeetingID")
                        .HasColumnType("int");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("PersonID");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("SacramentProgram.Models.Meeting", b =>
                {
                    b.HasOne("SacramentProgram.Models.Person", "Accompaniment")
                        .WithMany()
                        .HasForeignKey("AccompanimentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Person", "ClosingPrayerId")
                        .WithMany()
                        .HasForeignKey("ClosingPrayerIdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Song", "ClosingSong")
                        .WithMany()
                        .HasForeignKey("ClosingSongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Person", "Conducting")
                        .WithMany()
                        .HasForeignKey("ConductingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Song", "IntermediateSong")
                        .WithMany()
                        .HasForeignKey("IntermediateSongID");

                    b.HasOne("SacramentProgram.Models.Person", "LeadingMusic")
                        .WithMany()
                        .HasForeignKey("LeadingMusicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.MusicalNum", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberID");

                    b.HasOne("SacramentProgram.Models.Person", "OpeningPrayer")
                        .WithMany()
                        .HasForeignKey("OpeningPrayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Song", "OpeningSong")
                        .WithMany()
                        .HasForeignKey("OpeningSongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Person", "Presiding")
                        .WithMany()
                        .HasForeignKey("PresidingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SacramentProgram.Models.Song", "SacramentSong")
                        .WithMany()
                        .HasForeignKey("SacramentSongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SacramentProgram.Models.MusicalNum", b =>
                {
                    b.HasOne("SacramentProgram.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongID");
                });

            modelBuilder.Entity("SacramentProgram.Models.Speaker", b =>
                {
                    b.HasOne("SacramentProgram.Models.Meeting", "Meeting")
                        .WithMany("Speakers")
                        .HasForeignKey("MeetingID");

                    b.HasOne("SacramentProgram.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
